<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl;?>/css/xiumi-fix.css" />
<?php
$resourceUrl = Yii::app()->baseUrl . '/resource/overseas/surgery/';
$menu = $this->loadPageMenu();
?> 
<div class="row">
    <div  id="sidemenu" class="col-sm-3 hidden-xs pos-fixed">
        <div class="row">
            <div class="heading-u">
                <div class="text">海外名医</div>
                <div class="divider"></div>
            </div>
            <ul class="nav nav-pills nav-stacked">
                <?php
                foreach ($menu as $menuItem) {
                    echo '<li class="' . $menuItem['key'] . '"><a href="' . $menuItem['link'] . '"><i class="fa fa-chevron-right"></i>&nbsp;' . $menuItem['label'] . '</a></li>';
                }
                ?>
            </ul>
        </div>
    </div>
    <div class="col-sm-9 col-sm-offset-3">
        <div  class="inner ng-scope" ng-controller="BoardDeskController">
            <section id="article-content" class="tn-article-section container">
                <section class="">
                    <div class="heading-u">
                        <div class="text">特色手术</div>
                        <div class="divider"></div>
                    </div>
                </section>
                <section class="tn-board-body tn-article-content-context pb30">
                    <!-- ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>合作医院和医生可以为病人提供各色各样的手术治疗，在眼科、骨科、泌尿科和神经科等的手术更是达到国际顶尖水平。下面的先进手术供您参考：</section><section><br></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div id="surgery-1" class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; padding: 0px 2px 2px; box-sizing: border-box; border-bottom-width: 2px; border-bottom-style: solid; border-color: rgb(142, 201, 101); line-height: 1; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: center; text-decoration: inherit; color: white; background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable"><section style="display: inline-block; margin: 0px; padding: 0.3em 0.4em; min-width: 1.8em; min-height: 1.6em; border-radius: 80% 100% 90% 20%; line-height: 1; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; text-align: center; color: white; background-color: rgb(142, 201, 101);" ng-style="{ 'font-size': eo.fontSize, 'font-family': eo.fontFamily, 'font-style': eo.fontStyle, 'font-weight': eo.fontWeight,
                                                                                   'text-align': eo.textAlign, 'text-decoration': eo.textDecoration, 'color': eo.color , 'background-color': (eo.borderColor || theme.majorColor)}" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope ng-binding"><section>1</section></section><span style="display: inline-block; margin-left: 0.4em; max-width: 100%; color: rgb(0, 112, 192); line-height: 1.4;
                                                                                   font-size: 1em; word-wrap: break-word !important"><strong style="max-width: 100%; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; font-weight: bolder; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                  'font-size'       : eo.fontSize || 'inherit',
                                                  'font-family'     : eo.fontFamily || 'inherit',
                                                  'font-style'      : eo.fontStyle || 'inherit',
                                                  'font-weight'     : eo.fontWeight || 'inherit',
                                                  'text-align'      : eo.textAlign || 'inherit',
                                                  'text-decoration' : eo.textDecoration || 'inherit',
                                                  'color'           : (eo.color || theme.majorColor)
                                                  } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>无刀飞秒激光白内障手术</section></strong></span></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>新的技术使用飞秒激光进行切口代替传统白内障超声乳化术所用的金属刀片。在整个激光治疗过程在电脑控制“成像”的帮助下进行，能更好地控制切口并具有更高的可靠性，实现晶体囊的完美形状、尺寸以及精确定位以植入白内障镜片。人工晶体植入过程的准确定位和插入能最大可能地恢复患者视力。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl; ?>665cd74cb1342508ab7391c8d35fcbc9-sz_21383.jpg" tn-page-editable="img0" tn-page-editable-type="image" ng-src="<?php echo $resourceUrl; ?>665cd74cb1342508ab7391c8d35fcbc9-sz_21383.jpg" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl; ?>9ecde1225b1691eab0b8305fa6e67dce-sz_48103.jpg" tn-page-editable="img0" tn-page-editable-type="image" ng-src="<?php echo $resourceUrl; ?>9ecde1225b1691eab0b8305fa6e67dce-sz_48103.jpg" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div id="surgery-2" class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; padding: 0px 2px 2px; box-sizing: border-box; border-bottom-width: 2px; border-bottom-style: solid; border-color: rgb(142, 201, 101); line-height: 1; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: center; text-decoration: inherit; color: white; background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable"><section style="display: inline-block; margin: 0px; padding: 0.3em 0.4em; min-width: 1.8em; min-height: 1.6em; border-radius: 80% 100% 90% 20%; line-height: 1; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; text-align: center; color: white; background-color: rgb(142, 201, 101);" ng-style="{ 'font-size': eo.fontSize, 'font-family': eo.fontFamily, 'font-style': eo.fontStyle, 'font-weight': eo.fontWeight,
                                                                                   'text-align': eo.textAlign, 'text-decoration': eo.textDecoration, 'color': eo.color , 'background-color': (eo.borderColor || theme.majorColor)}" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope ng-binding"><section>2</section></section><span style="display: inline-block; margin-left: 0.4em; max-width: 100%; color: rgb(0, 112, 192); line-height: 1.4;
                                                                                   font-size: 1em; word-wrap: break-word !important"><strong style="max-width: 100%; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; font-weight: bolder; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                  'font-size'       : eo.fontSize || 'inherit',
                                                  'font-family'     : eo.fontFamily || 'inherit',
                                                  'font-style'      : eo.fontStyle || 'inherit',
                                                  'font-weight'     : eo.fontWeight || 'inherit',
                                                  'text-align'      : eo.textAlign || 'inherit',
                                                  'text-decoration' : eo.textDecoration || 'inherit',
                                                  'color'           : (eo.color || theme.majorColor)
                                                  } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>肾癌切除术</section></strong></span></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>早期肾癌切除术的目的是维护您的健康的肾脏组织，其特点是优良的临床效果和控制癌症。切除术可以防止潜在的肾脏疾病，住院时间短，精确的肿瘤切除，肾重建，保留剩余健康的肾脏。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl; ?>e14b445c84c9b649a21c4fc16b0a168c-sz_5051.jpg" tn-page-editable="img0" tn-page-editable-type="image" ng-src="<?php echo $resourceUrl; ?>e14b445c84c9b649a21c4fc16b0a168c-sz_5051.jpg" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div id="surgery-3" class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; padding: 0px 2px 2px; box-sizing: border-box; border-bottom-width: 2px; border-bottom-style: solid; border-color: rgb(142, 201, 101); line-height: 1; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: center; text-decoration: inherit; color: white; background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable"><section style="display: inline-block; margin: 0px; padding: 0.3em 0.4em; min-width: 1.8em; min-height: 1.6em; border-radius: 80% 100% 90% 20%; line-height: 1; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; text-align: center; color: white; background-color: rgb(142, 201, 101);" ng-style="{ 'font-size': eo.fontSize, 'font-family': eo.fontFamily, 'font-style': eo.fontStyle, 'font-weight': eo.fontWeight,
                                                                                   'text-align': eo.textAlign, 'text-decoration': eo.textDecoration, 'color': eo.color , 'background-color': (eo.borderColor || theme.majorColor)}" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope ng-binding"><section>3</section></section><span style="display: inline-block; margin-left: 0.4em; max-width: 100%; color: rgb(0, 112, 192); line-height: 1.4;
                                                                                   font-size: 1em; word-wrap: break-word !important"><strong style="max-width: 100%; word-wrap: break-word !important; font-size: 1em; font-family: inherit; font-style: normal; font-weight: bolder; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                  'font-size'       : eo.fontSize || 'inherit',
                                                  'font-family'     : eo.fontFamily || 'inherit',
                                                  'font-style'      : eo.fontStyle || 'inherit',
                                                  'font-weight'     : eo.fontWeight || 'inherit',
                                                  'text-align'      : eo.textAlign || 'inherit',
                                                  'text-decoration' : eo.textDecoration || 'inherit',
                                                  'color'           : (eo.color || theme.majorColor)
                                                  } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>清醒开颅手术</section></strong></span></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>脑瘤目前公认的治疗手段为开颅手术切除肿瘤，医生将在患者大脑中受到病变或肿瘤的一部分区域进行手术。重要的是患者在整个过程中是有意识的，这可以让医生在手术过程中监控大脑的重要功能。虽然患者会保持清醒，但不会感到任何不适。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl; ?>2dca87754cf5423035c8ddac3fcbd3df-sz_219734.jpg" tn-page-editable="img0" tn-page-editable-type="image" ng-src="<?php echo $resourceUrl; ?>2dca87754cf5423035c8ddac3fcbd3df-sz_219734.jpg" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe">顶尖手术成功率高，风险小，设备先进，治疗环境好，为病人提供专属的优质服务。</fieldset></div></div>
                    </div>
                </section>
            </section>
        </div>
    </div>
</div>