<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/xiumi-fix.css" />

<?php
$resourceUrl = Yii::app()->baseUrl . '/resource/article/';
?>
<div class="row">

    <div class="col-sm-9 col-sm-offset-2">
        <div class="inner ng-scope" ng-controller="BoardDeskController">
            <section id="xiumi-content" class="tn-article-section container">
                <section class="">
                    <div class="heading-u">
                        <div class="text">睡眠日拥有完美的睡眠不再受失眠困扰</div>
                        <div class="divider"></div>
                    </div>
                </section>
                <section class="tn-board-body tn-article-content-context">
                    <!-- ngIf: !showData -->

                    <!-- ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>亲爱的，你的睡眠好吗？让我们一起来测试一下吧！<br></section><section>下面有10个问题，请根据实际情况分别选择：“A经常B有时C很少D从未”，四个答案。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl;?>article8.1.jpg" tn-page-editable="img0" tn-page-editable-type="image" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>1.睡眠时间很不规律，不能按时上床睡眠。<br></section><section>2.工作或娱乐至深夜。<br></section><section>3.躺在床上脑子里全是白天见过的人和发生的事，难以入睡。<br></section><section>4.入睡后稍有动静就能知道。<br></section><section>5.整夜做梦，醒来时觉得很累。<br></section><section>6.很早就醒来，而且再也睡不着了。<br></section><section>7.有点不顺心的事就彻夜难眠。<br></section><section>8.换个地方就难以入睡。<br></section><section>9.上夜班就睡眠不好。<br></section><section>10.使用安眠药才能安然入睡。你的睡眠质量好吗？<br></section><section>选中A记5分，B记2分，C记1分，D记0分。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>如果您的总分在20分以上为严重睡眠障碍。总分在5~20分说明您的睡眠质量比较差。5分以下（没有A项）说明您的睡眠质量良好。如果您的累计得分在5分以上，特别是有A项得分，您需要高度重视您的睡眠状况，想办法改善睡眠质量。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;text-align: left; margin: 0.8em 0 0.5em 0" class="ng-scope"><span style="display: inline-block; padding: 0.3em 0.5em; border-radius: 0.5em; color: white; text-align: inherit; font-size: 131.25%; box-shadow: rgb(165, 165, 165) 0.2em 0.2em 0.1em; font-family: inherit; font-style: normal; font-weight: inherit; text-decoration: inherit; border-color: rgb(249, 110, 87); background-color: rgb(142, 201, 101);" tn-page-editable="richtext0" tn-not-editable-attr="borderColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>如何调节睡眠</section></span></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>1</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(42, 52, 58);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>适当放松自己</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl;?>article8.2.jpg" tn-page-editable="img0" tn-page-editable-type="image" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>人的睡眠分为生理睡眠和心理睡眠 两个阶段。生理睡眠就是指人每天的睡眠时间若有达到3.5个小时，就完全可以满足人体的需要。而心理睡眠就是人的潜意识对睡眠的一种满足感。所以临睡前越放松越好，不要担心自己今天可能还只是睡三四个小时，担心睡眠不足影响第二天的工作。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>2</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(42, 52, 58);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>不要太计较睡眠的量</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>睡眠量的要求是因人而异的，一个人一天并非一定要睡上7个或8个小时，合理的睡眠量应以能解除疲劳，保持精神愉快，能很好地进行一天的工作与学习为标准。相反，如果对睡眠的量过分计较，常因少睡半小时而心神不定，对"睡个好觉"只能是有害无益。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>3</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(42, 52, 58);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>养成良好饮食习惯</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl;?>article8.3.jpg" tn-page-editable="img0" tn-page-editable-type="image" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>晚餐不要吃得太饱，或空腹睡觉，这二种情况都会影响人的睡眠。临睡前吃点奶制品或喝一杯牛奶有助于睡眠。睡前忌饮大量含酒精的饮料、咖啡、茶、可乐饮料及巧克力，因对人的大脑神经能产生兴奋作用，不利于睡眠。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>4</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(42, 52, 58);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>让床只发挥睡眠的功能</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>不要让床成为你学习、工作的场所。躺在床上看书、看报，或谈些兴奋性的话题，会削弱床与睡眠的直接联系。一个良好的睡眠者，往往是"头一挨着枕头就能入睡"，这是因为他长期以来只让床发挥单一睡眠功能的结果，以至于形成了条件反射。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>5</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(42, 52, 58);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>别做激烈运动</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>记得睡前不要做太过剧烈的运，因为会使身体太过兴奋而难以入眠。可以在睡前作一些简单的伸展运或瑜珈，可以让你松弛肌肉，舒解紧绷情绪。伸展肌肉几秒钟，然后再放松，这有助于纾解压力，放松后的筋骨能让你更容易进入梦乡。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 75%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: right; text-decoration: inherit; color: rgb(95, 156, 239);" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>文章来自网络，转自营养圣经</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices -->
                </section>
        </div>
    </div>
</div>