<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/xiumi-fix.css" />

<?php
$resourceUrl = Yii::app()->baseUrl . '/resource/article/';
?>
<div class="row">

    <div class="col-sm-9 col-sm-offset-2">
        <div class="inner ng-scope" ng-controller="BoardDeskController">
            <section id="xiumi-content" class="tn-article-section container">
                <section class="">
                    <div class="heading-u">
                        <div class="text">睡眠日拥有完美的睡眠不再受失眠困扰</div>
                        <div class="divider"></div>
                    </div>
                </section>
                <section class="tn-board-body tn-article-content-context">
                    <!-- ngIf: !showData -->

                    <!-- ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>切开法是在眼皮上，以患者要求的高度和形态划设计线，并按设计线切开皮肤后祛除并调整必要的皮肤、肌肉、脂肪、结缔组织，是在上睑皮肤厚、脂肪多，埋线法容易松解的时候做的手术方法。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope"><img style="box-sizing: border-box;
                                                                                                                                                                                                        width: 100%;
                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                        text-align: start" src="<?php echo $resourceUrl;?>article9.1.jpg" tn-page-editable="img0" tn-page-editable-type="image" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;text-align: left; margin: 0.8em 0 0.5em 0" class="ng-scope"><span style="display: inline-block; padding: 0.3em 0.5em; border-radius: 0.5em; color: white; text-align: inherit; font-size: 1em; box-shadow: rgb(165, 165, 165) 0.2em 0.2em 0.1em; font-family: inherit; font-style: normal; font-weight: inherit; text-decoration: inherit; border-color: rgb(249, 110, 87); background-color: rgb(142, 201, 101);" tn-page-editable="richtext0" tn-not-editable-attr="borderColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>优点</section></span></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: normal; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>1、具有可恢复性。<br></section><section>就是说如果对重睑手术后效果不满意或难以适应术后的形态，只要拆除缝线就可以恢复到原来的形态。当然手术前就预想这种可能性而做手术不太满意罕见。但对手术的可恢复性来说，埋线法的适用范围是非常广的。</section><section><br></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>2、韩式双眼皮效果非常自然，非常逼真，术后别人不会看到有任何的疤痕。</section><section><br></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>3、韩式双眼皮治疗时间只有短短的20几分钟，非常的方便。</section><section><br></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>4、韩式双眼皮治疗过程非常轻松，不会有任何的痛苦感，能够让您在轻松的状态下完成韩式双眼皮治疗。</section><section><br></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>5、韩式双眼皮术后恢复时间非常快，几天就可以完全恢复，爱美的您就可以参加各种各样的活动了。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;text-align: left; margin: 0.8em 0 0.5em 0" class="ng-scope"><span style="display: inline-block; padding: 0.3em 0.5em; border-radius: 0.5em; color: white; text-align: inherit; font-size: 1em; box-shadow: rgb(165, 165, 165) 0.2em 0.2em 0.1em; font-family: inherit; font-style: normal; font-weight: inherit; text-decoration: inherit; border-color: rgb(249, 110, 87); background-color: rgb(142, 201, 101);" tn-page-editable="richtext0" tn-not-editable-attr="borderColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>手术方法</section></span></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>一、切开法双眼皮手术</section><section>关于上睑皮肤松懈、上睑痴肥、三角眼及内眦赘皮者，采用切开法做双眼皮手术结果最佳，对用埋线法或缝线法做双眼皮后效果不理想者，都可用此法来弥补，且术后不易复发单睑。</section><section><br></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>二、埋线法双眼皮手术</section><section>通过小的皮肤切断，将缝线埋在皮下的一种办法。适应那些上睑眶隔脂肪少，皮肤薄而紧的年轻人，也适合一侧单睑者或重睑时隐时现者，或双眼皮后重睑皱褶部分变浅或消逝需要进行双眼皮修复的求美者。</section><section><br></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>三、韩式三点双眼皮构成法</section><section>三点双眼皮构成法，就是在眼睑上开三个小切口，依照医生所画线进行手术操作，画线是为了达到最佳的手术结果，该双眼皮法具有上述两种重睑术的优势，再加上韩式微创的精秒技术所形成的双眼皮结果极佳，形状天然，手术恢复工夫短。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices -->
                </section>
        </div>
    </div>
</div>