<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/xiumi-fix.css" />

<?php
$resourceUrl = Yii::app()->baseUrl . '/resource/article/';
?>
<div class="row">

    <div class="col-sm-9 col-sm-offset-2">
        <div class="inner ng-scope" ng-controller="BoardDeskController">
            <section id="xiumi-content" class="tn-article-section container">
                <section class="">
                    <div class="heading-u">
                        <div class="text">保养血管从30岁开始</div>
                        <div class="divider"></div>
                    </div>
                </section>

                <section class="tn-board-body tn-article-content-context">

                    <div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>很多人以为，人只有到老了才会为血管操心。殊不知，30岁以后，人体内的血管斑块就开始出现并变大。虽然很多人表面看起来精力充沛，连感冒都很少得，其实身体里的血管已经悄悄老化，慢慢失去弹性，再加上现代人生活节奏快、压力大、饮食不健康、运动量少，因此血管会在不知不觉中衰老和损坏。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope">
                                    <img style="box-sizing: border-box;
                                         width: 100%;
                                         height: auto !important;
                                         text-align: start" src="<?php echo $resourceUrl; ?>article7.1.jpg" tn-page-editable="img0" tn-page-editable-type="image" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>人体每6.5平方厘米的皮肤上就分布着长约6.1米的血管，好的血管富有活力，血管口径大、管壁光滑、柔软、弹性好，输送血液的能力也强。而不注重保养的血管就像用了很长时间的自来水管，管道内壁结垢、生锈，导致管道受阻而无法供水。血液中的“水垢”就是胆固醇、甘油三酯等，它们在血管壁上越积越多，形成如同黄色小米样的斑块。久而久之，血管壁弹力下降，血液流动受阻，最终因缺血引起心、脑血管病。那么该如何保养血管呢？保养血管要从吃和动两方面入手。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;display: inline-block; margin: 0.8em 0 0.5em; line-height: 1; white-space: nowrap; overflow: hidden" class="ng-scope"><section style="border-bottom-style: solid; border-bottom-width: 1px; border-color: rgb(142, 201, 101); font-size: 1.4em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: white; background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable"><section style="display: inline-block; height: 1.2em; padding: 0.1em; line-height: 1em; font-size: 1.4em; font-family: inherit; font-style: normal; color: white; background-color: rgb(142, 201, 101);" ng-style="{ 'font-size': eo.fontSize, 'font-family': eo.fontFamily, 'font-style': eo.fontStyle, 'font-weight': eo.fontWeight,
                                                                                   'text-align': eo.textAlign, 'text-decoration': eo.textDecoration, 'color': eo.color,
                                                                                   'background-color': (eo.borderColor || theme.majorColor) }" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope ng-binding"><section>吃</section></section><section style="display: inline-block; padding: 0.2em; line-height: 1; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(42, 52, 58);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                   'font-size'       : eo.fontSize || 'inherit',
                                                                                   'font-family'     : eo.fontFamily || 'inherit',
                                                                                   'font-style'      : eo.fontStyle || 'inherit',
                                                                                   'font-weight'     : eo.fontWeight || 'inherit',
                                                                                   'text-align'      : eo.textAlign || 'inherit',
                                                                                   'text-decoration' : eo.textDecoration || 'inherit',
                                                                                   'color'           : (eo.color || theme.majorColor)
                                                                                   } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>血液“清道夫”</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 131.25%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>1</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: normal; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>吃含鱼油多的食品</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>鱼肉富含甲硫氨酸、赖氨酸、脯氨酸及牛黄氨酸，有改善血管弹性、顺应性及促进钠盐排泄的作用。富含ω-3多不饱和脂肪酸的鱼油还有保护血管内皮细胞、减少脂质沉积及改善纤溶的功能。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 131.25%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>2</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>多吃富含精氨酸和叶酸的食物</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>多吃富含精氨酸的食物有助于调节血管张力、抑制血小板聚集，减少血管损伤，例如海参、泥鳅、鳝鱼及芝麻、山药、银杏、豆腐皮、葵花子等。膳食中缺乏叶酸及维生素B6、B12，会使血中半胱氨酸水平升高，易损伤血管内皮细胞，促进粥样硬化斑块形成。富含叶酸的食物有红苋菜、菠菜、龙须菜、芦笋、豆类及苹果、柑橘等。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;box-sizing: border-box; width: 100%; margin: 0.8em 0 0.2em 0;clear: both" class="ng-scope">
                                    <img style="box-sizing: border-box;
                                         width: 100%;
                                         height: auto !important;
                                         text-align: start" src="<?php echo $resourceUrl; ?>article7.2.jpg" tn-page-editable="img0" tn-page-editable-type="image" class="ng-scope tn-page-editable"></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 131.25%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>3</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>多吃天然抗凝与降脂食物</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>具有抑制血小板聚集和一定抗凝作用的食物有黑木耳、洋葱、茼蒿、香菇、草莓、菠萝等。番茄、葡萄、橘子中含少量类似阿司匹林的水杨酸抗凝物质。降脂食物有螺旋藻、香芹、胡萝卜、山楂、紫菜、海带、核桃及橄榄油、芝麻油等。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;margin: 0.8em 0 0.5em 0" class="ng-scope"><section style="display: inline-block; float: left; width: 1.2em; height: 1.2em; border-radius: 50%; padding: 0.1em; margin-right: 0.3em; vertical-align: top; text-align: center; box-sizing: border-box; border: 1px solid rgb(142, 201, 101); line-height: 1; font-size: 131.25%; font-family: inherit; font-style: normal; font-weight: bolder; text-decoration: inherit; color: rgb(142, 201, 101); background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } "><section>4</section></section><section style="margin-left: 0.3em; vertical-align: bottom"><section style="line-height: 1.2; font-size: 112.5%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(142, 201, 101);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                           'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                           'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                           'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                           'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                           'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                           'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                           'color'           : (eo.color || theme.majorColor)
                                                                                                                                           } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>喝绿茶</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>绿茶中的儿茶酚能减少血液中坏胆固醇的含量，增加好胆固醇的含量，增加血管柔韧性、弹性，预防血管硬化。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border:0;display: inline-block; margin: 0.8em 0 0.5em; line-height: 1; white-space: nowrap; overflow: hidden" class="ng-scope"><section style="border-bottom-style: solid; border-bottom-width: 1px; border-color: rgb(142, 201, 101); font-size: 1.4em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: white; background-color: transparent;" tn-page-editable="richtext0" tn-not-editable-attr="backgroundColor" tn-page-editable-type="ed-type-rich-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor),
                                                                                                                                                                                                        'background-color': (eo.backgroundColor || theme.majorColor),
                                                                                                                                                                                                        'border-color'    : (eo.borderColor || theme.majorColor)
                                                                                                                                                                                                        } " class="ng-scope tn-page-editable"><section style="display: inline-block; height: 1.2em; padding: 0.1em; line-height: 1em; font-size: 1.4em; font-family: inherit; font-style: normal; color: white; background-color: rgb(142, 201, 101);" ng-style="{ 'font-size': eo.fontSize, 'font-family': eo.fontFamily, 'font-style': eo.fontStyle, 'font-weight': eo.fontWeight,
                                                                                   'text-align': eo.textAlign, 'text-decoration': eo.textDecoration, 'color': eo.color,
                                                                                   'background-color': (eo.borderColor || theme.majorColor) }" ng-bind-html="eo.text | eol2br | unsafe" class="tn-rich-text-content ng-scope ng-binding"><section>请</section></section><section style="display: inline-block; padding: 0.2em; line-height: 1; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: inherit; text-decoration: inherit; color: rgb(42, 52, 58);" tn-page-editable="text1" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                   'font-size'       : eo.fontSize || 'inherit',
                                                                                   'font-family'     : eo.fontFamily || 'inherit',
                                                                                   'font-style'      : eo.fontStyle || 'inherit',
                                                                                   'font-weight'     : eo.fontWeight || 'inherit',
                                                                                   'text-align'      : eo.textAlign || 'inherit',
                                                                                   'text-decoration' : eo.textDecoration || 'inherit',
                                                                                   'color'           : (eo.color || theme.majorColor)
                                                                                   } " ng-bind-html="eo.text | eol2br | unsafe" class="ng-scope tn-page-editable ng-binding"><section>保养血管离不开运动</section></section></section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 1em; font-family: inherit; font-style: normal; font-weight: inherit; text-align: justify; text-decoration: inherit; color: inherit;" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>每天运动半小时，如走路、骑自行车、游泳、打门球、打乒乓球、慢跑、游泳、爬楼或登山，都能起到减肥消脂、预防血管老化的作用。如果饭前运动，保护血管的效果更好。</section><section><br></section><section>身体状态允许的人晚上睡前可进行冷热水交替淋浴，热水温度为40℃~44℃，冷水温度为12℃~16℃。先冷后热，交替5~10次，每次持续2~3分钟，最后以热水浴结束。</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices --><div class="x3-slice-plate clearfix ng-scope" ng-repeat="slice in slices">
                        <div class="tn-slice-loader ng-isolate-scope" tn-page-loader="" page="slice" tn-page-show-with-transition="true" theme="(slice.themeColor | clr2theme)" template-path="/templates/parts"><!-- ngInclude: (page.templateId) | templateIdToPath: templatePath --><div class="tn-page ng-scope" ng-include="(page.templateId) | templateIdToPath: templatePath"><fieldset style="border: 0px; margin-top: 0px; margin-bottom: 0px; clear: both; font-size: 75%; font-family: inherit; font-style: normal; font-weight: inherit; text-align: right; text-decoration: inherit; color: rgb(95, 156, 239);" tn-page-editable="text0" class="ng-scope tn-page-editable ng-binding" tn-page-editable-type="ed-type-text" ng-style=" {
                                                                                                                                                                                                        'font-size'       : eo.fontSize || 'inherit',
                                                                                                                                                                                                        'font-family'     : eo.fontFamily || 'inherit',
                                                                                                                                                                                                        'font-style'      : eo.fontStyle || 'inherit',
                                                                                                                                                                                                        'font-weight'     : eo.fontWeight || 'inherit',
                                                                                                                                                                                                        'text-align'      : eo.textAlign || 'inherit',
                                                                                                                                                                                                        'text-decoration' : eo.textDecoration || 'inherit',
                                                                                                                                                                                                        'color'           : (eo.color || theme.majorColor)
                                                                                                                                                                                                        } " ng-bind-html="eo.text | eol2br | unsafe"><section>内容和图片源自网络</section></fieldset></div></div>
                    </div><!-- end ngRepeat: slice in slices -->
                </section>





            </section>
        </div>
    </div>
</div>